#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 0 ]; then
    echo "Usage: $0 < infile"
    exit 1
fi

javac Prims.java
# Run the Java program with input from standard input
java Prims
